window.moderate_dots_spacing = {
    padding: 50,
    spacing: 50,
    rows: 10,
    columns: 30,
    svgBackgroundColor: 'white',
    DISTANCE_TO_FEAR: 100,
    DISTANCE_TO_STEP: 30,
    DELAY_BEFORE_GOING_HOME: 200,
    DOT_RADIUS: 5,
    DOT_COLOR_PATTERN: 'vertical',
    PATTERN_COLORS: [
        'red',
        'orange',
        'yellow',
        'green',
        'cyan',
        'skyblue',
        'blue',
        'indigo',
        'violet',
        'lightgrey',
    ],
    CSS_CLASS_GOING_HOME: 'animate_going_home',
    transitions: {
        timing: {
            fromHome: 'ease',
            backHome: 'ease',
        },
        duration: {
            fromHome: '0.1s',
            backHome: '1s',
        },
    },
};

window.tenK_smalls_dots = {
    padding: 10,
    spacing: 10,
    rows: 100,
    columns: 100,
    svgBackgroundColor: 'white',
    DISTANCE_TO_FEAR: 100,
    DISTANCE_TO_STEP: 30,
    DELAY_BEFORE_GOING_HOME: 200,
    DOT_RADIUS: 2,
    DOT_COLOR_PATTERN: 'random',
    PATTERN_COLORS: [
        'red',
        'orange',
        'yellow',
        'green',
        'cyan',
        'skyblue',
        'blue',
        'indigo',
        'violet',
        'lightgrey',
    ],
    CSS_CLASS_GOING_HOME: 'animate_going_home',
    transitions: {
        timing: {
            fromHome: 'ease',
            backHome: 'ease',
        },
        duration: {
            fromHome: '0.1s',
            backHome: '1s',
        },
    },
};

window.spaced_large_dots = {
    padding: 50,
    spacing: 120,
    rows: 5,
    columns: 5,
    svgBackgroundColor: 'white',
    DISTANCE_TO_FEAR: 100,
    DISTANCE_TO_STEP: 30,
    DELAY_BEFORE_GOING_HOME: 200,
    DOT_RADIUS: 50,
    DOT_COLOR_PATTERN: 'random',
    PATTERN_COLORS: [
        'red',
        'orange',
        'yellow',
        'green',
        'cyan',
        'skyblue',
        'blue',
        'indigo',
        'violet',
        'lightgrey',
    ],
    CSS_CLASS_GOING_HOME: 'animate_going_home',
    transitions: {
        timing: {
            fromHome: 'ease',
            backHome: 'ease',
        },
        duration: {
            fromHome: '0.1s',
            backHome: '1s',
        },
    },
};

window.spaced_medium_dots = {
    padding: 50,
    spacing: 50,
    rows: 10,
    columns: 30,
    svgBackgroundColor: 'white',
    DISTANCE_TO_FEAR: 50,
    DISTANCE_TO_STEP: 30,
    DELAY_BEFORE_GOING_HOME: 200,
    DOT_RADIUS: 20,
    DOT_COLOR_PATTERN: 'diagonal',
    PATTERN_COLORS: [
        'red',
        'orange',
        'yellow',
        'green',
        'cyan',
        'skyblue',
        'blue',
        'indigo',
        'violet',
        'lightgrey',
    ],
    CSS_CLASS_GOING_HOME: 'animate_going_home',
    transitions: {
        timing: {
            fromHome: 'ease',
            backHome: 'ease',
        },
        duration: {
            fromHome: '0.1s',
            backHome: '1s',
        },
    },
}

window.dense_group = {
    padding: 50,
    spacing: 20,
    rows: 20,
    columns: 20,
    svgBackgroundColor: 'white',
    DISTANCE_TO_FEAR: 25,
    DISTANCE_TO_STEP: 10,
    DELAY_BEFORE_GOING_HOME: 200,
    DOT_RADIUS: 20,
    DOT_COLOR_PATTERN: 'diagonal',
    PATTERN_COLORS: [
        'red',
        'orange',
        'yellow',
        'green',
        'cyan',
        'skyblue',
        'blue',
        'indigo',
        'violet',
        'lightgrey',
    ],
    CSS_CLASS_GOING_HOME: 'animate_going_home',
    transitions: {
        timing: {
            fromHome: 'ease',
            backHome: 'ease',
        },
        duration: {
            fromHome: '0.1s',
            backHome: '1s',
        },
    },
};
